name: /ocean/projects/cis240101p/mzhang23/TA/HW4/envs/hw4_env
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.2
  - pthread-stubs=0.3
  - python=3.11.13
  - readline=8.3
  - sqlite=3.50.2
  - tk=8.6.15
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - annotated-types==0.7.0
      - anyio==4.8.0
      - appnope==0.1.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.4
      - attrs==25.1.0
      - babel==2.17.0
      - beautifulsoup4==4.13.3
      - bleach==6.2.0
      - certifi==2024.12.14
      - cffi==1.17.1
      - charset-normalizer==3.4.0
      - click==8.1.8
      - comm==0.2.2
      - contourpy==1.3.1
      - cycler==0.12.1
      - debugpy==1.8.12
      - decorator==5.2.1
      - defusedxml==0.7.1
      - docker-pycreds==0.4.0
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - filelock==3.16.1
      - fonttools==4.55.3
      - fqdn==1.5.1
      - fsspec==2024.10.0
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.27.0
      - idna==3.10
      - importlib-metadata==8.6.1
      - ipykernel==6.29.5
      - ipython==9.0.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.4
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - kaggle==1.7.4.2
      - kiwisolver==1.4.7
      - lightning-utilities==0.12.0
      - markupsafe==3.0.2
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.7
      - mistune==3.1.2
      - mpmath==1.3.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - notebook==7.3.2
      - notebook-shim==0.2.4
      - numpy==2.2.0
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==11.0.0
      - platformdirs==4.3.6
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.50
      - protobuf==5.29.3
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.22
      - pydantic==2.10.5
      - pydantic-core==2.27.2
      - pygments==2.19.1
      - pyparsing==3.2.0
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.2.1
      - python-slugify==8.0.4
      - pytz==2024.2
      - pyyaml==6.0.2
      - pyzmq==26.2.1
      - referencing==0.36.2
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.23.1
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentry-sdk==2.19.2
      - setproctitle==1.3.4
      - setuptools==78.1.0
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - sympy==1.13.1
      - terminado==0.18.1
      - text-unidecode==1.3
      - tinycss2==1.4.0
      - tokenizers==0.21.0
      - torch==2.5.1
      - torchaudio==2.5.1
      - torchinfo==1.8.0
      - torchmetrics==1.6.1
      - torchsummary==1.1
      - torchsummaryx==1.1.0
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triton==3.1.0
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.12.2
      - typing-inspection==0.4.0
      - tzdata==2024.2
      - uri-template==1.3.0
      - urllib3==2.3.0
      - wandb==0.19.9
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - wheel==0.44.0
      - widgetsnbextension==4.0.13
      - zipp==3.21.0
prefix: /ocean/projects/cis240101p/mzhang23/TA/HW4/envs/hw4_env
