# Sampling / scheduler
use_ddim: true  # use DDIM sampler
ddim_eta: 0.0   # matches args.ddim_eta
clip_sample: true
clip_sample_range: 1.0

#Paths
run_name: imagenet100_ddim
output_dir: ddim_trained_models

# Using the common dataset folder
data_dir: /jet/home/jgupta2/hw5_student_starter_code/data/imagenet100_128x128/train
val_dir:  /jet/home/jgupta2/hw5_student_starter_code/data/imagenet100_128x128/validation

#Data / training
seed: 42
image_size: 128
batch_size: 32  # like Juhi and we used in the CLI for CIFAR10
num_workers: 8
num_classes: 100
num_epochs: 100
learning_rate: 2.0e-4
weight_decay: 1.0e-5

# Diffusion schedule
num_train_timesteps: 1000
num_inference_steps: 250
beta_start: 1.0e-4
beta_end: 0.02
beta_schedule: linear

variance_type: fixed_small
prediction_type: epsilon

# UNet
unet_in_size: 32 # UNet input size (patch-ified)
unet_in_ch: 3
unet_ch: 128
unet_num_res_blocks: 2
unet_ch_mult: [1, 2, 2, 4]
unet_attn: [2, 3]
unet_dropout: 0.1

#  Extra features
latent_ddpm: false
use_cfg: false

# FID / IS evaluation
eval_fid_is: true
eval_samples: 1000
eval_frequency: 5
