# SPECIFY RUN-NAME
run_name: "SK-ddim_cfg_192-2346-07Dec"

# Sampling / scheduler
model_type: "unet"
use_ddim: true  # use DDIM sampler
ddim_eta: 0.0   # matches args.ddim_eta
clip_sample: true
clip_sample_range: 1.0

#Paths
output_dir: experiments

# Using the common dataset folder
data_dir: /jet/home/jgupta2/hw5_student_starter_code/data/imagenet100_128x128/train
val_dir:  /jet/home/jgupta2/hw5_student_starter_code/data/imagenet100_128x128/validation

#Data / training
seed: 42
image_size: 128
batch_size: 32  # like Juhi and we used in the CLI for CIFAR10
num_workers: 0 # Switched from 8-->2-->0 due to RuntimeError in DataLoader worker process 0.
num_classes: 100
num_epochs: 200
patience: 100 # For early-stopping
learning_rate: 2.0e-4
weight_decay: 1.0e-5

# Diffusion schedule
num_train_timesteps: 1000
num_inference_steps: 500
beta_start: 1.0e-4
beta_end: 0.02
beta_schedule: cosine

variance_type: fixed_small
prediction_type: epsilon

# UNet
unet_in_size: 128 # UNet input size 
unet_in_ch: 3
unet_ch: 128
unet_num_res_blocks: 2
unet_ch_mult: [1, 2, 2, 4]
unet_attn: [2, 3]
unet_dropout: 0.1

#  Extra features
latent_ddpm: false
use_cfg: true
cfg_guidance_scale: 2.0

# FID / IS evaluation
eval_fid_is: true
eval_samples: 1000
eval_frequency: 5
